syntax on
filetype plugin indent on

augroup RCVisual
  autocmd GUIEnter *  colorscheme vividchalk
augroup END

runtime! autoload/pathogen.vim
if exists("g:loaded_pathogen")
  call pathogen#runtime_append_all_bundles()
end

if (has('gui_running'))
  set guifont=Monaco:h16
  set guioptions=egmrLtT
  set columns=100
  set lines=42
  set number
endif

set clipboard=exclude:.*

nmap <silent> <F1> <Esc>:%s/\s\+$//gi<CR>

iabbrev rdebug require 'ruby-debug'; Debugger.start; debugger

