syntax on
filetype plugin indent on

augroup RCVisual
  autocmd GUIEnter *  colorscheme vividchalk
  autocmd GUIEnter *  set go-=T
augroup END

augroup mkd
  autocmd BufRead *.md  set ai formatoptions=tcroqn2 comments=n:>
augroup END


runtime! autoload/pathogen.vim
if exists("g:loaded_pathogen")
  call pathogen#runtime_append_all_bundles()
end

if (has('gui_running'))
  set guifont=Monaco:h16
  set guioptions=egmrLtT
  set columns=100
  set lines=42
endif

set clipboard=exclude:.*
set vb
set splitbelow
set splitright
set hidden

nmap <silent> <F1> <Esc>:%s/\s\+$//gi<CR>

iabbrev rdebug require 'ruby-debug'; Debugger.start; debugger
iabbrev bound puts '*'*80

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

