# path (for some reason, I can't use $PATH in the path array declaration, so 
# I'm setting it to it's literal value of: /opt/local/bin /opt/local/sbin 
# /usr/bin /bin /usr/sbin /sbin /usr/X11/bin)
path=(
  "$HOME/bin"
  "$HOME/ruby/gems/1.8/bin/"
  /usr/local/bin
  /usr/local/sbin
  /usr/local/mysql/bin
  /usr/local/pgsql/bin
  /usr/local/ec2/bin
  /opt/local/bin
  /opt/local/sbin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /usr/X11/bin
  /usr/local/libexec/git-core
)

# color term
export CLICOLOR=1
export LSCOLORS=Dxfxcxdxbxegedabadacad
export ZLS_COLORS=$LSCOLORS
export TERM=xterm
export LC_CTYPE=en_US.UTF-8
export LESS=FRX

# make with the nice completion
autoload -U compinit; compinit

# make with the pretty colors
autoload colors; colors

# teh opchunz
setopt appendhistory autocd extendedglob histignoredups correctall

# places I lurk
cdpath=(~ ~/development ~/development/hashrock ..)

# prompt
PROMPT="%{$fg[yellow]%}%~ %{$reset_color%}%# "
# if on a remote host, show host name
[[ -n "$SSH_CLIENT" ]] && PROMPT="$HOST:$PROMPT"
# if running screen, show window #
[[ x$WINDOW != x ]] && PROMPT="$WINDOW:$PROMPT"
# show non success exit codes in right prompt
RPROMPT="%(?..{%{$fg[red]%}%?%{$reset_color%}})"

# history
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=10000

# default apps
(( ${+BROWSER} )) || export BROWSER='lynx'
(( ${+PAGER} ))   || export PAGER='less'
(( ${+EDITOR}))   || export EDITOR='vim'

# just say no to zle vim mode:
bindkey -e

# aliases
alias mv='nocorrect mv'       # no spelling correction on mv
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'
alias ll="ls -l"
alias l.='ls -ld .[^.]*'
alias lsd='ls -ld *(-/DN)'
alias md='mkdir -p'
alias rd='rmdir'
alias cd..='cd ..'
alias ..='cd ..'
alias spec='spec -c'

# hashrocket stuffs
export HASHROCKET_DIR="$HOME/development/hashrock"
hpd="$HOME/.hash_profile_dev"
[[ -a $hpd ]] && source $hpd

# ruby stuffs
export GEM_HOME="$HOME/ruby/gems/1.8"

