#!/usr/bin/env ruby

cwd = File.expand_path(File.dirname(__FILE__))
home = File.expand_path('~')

# symlink all the files in the dotfiles dir into place
Dir[File.join(cwd,'dotfiles','*')].each do |file|
  target = File.join(home, ".#{File.basename(file)}")
  `ln -s #{File.expand_path(file)} #{target}`
end

#symlink in my bin dir
`ln -s #{File.join(cwd,'bin')} #{File.join(home,'bin')}`

