#!/usr/bin/env ruby

def cwd
  @cwd ||= File.expand_path(File.dirname(__FILE__))
end

def home
  @home ||= File.expand_path('~')
end

def install_to_home(file,sub_directory=nil)
  dirs = [home, sub_directory, File.basename(file)].compact
  dest = File.join(*dirs)
  src  = File.expand_path(file)
  if system("ln -nsf #{src} #{dest}")
    print "successfully installed "
  else
    print "failed to install "
  end
  puts dest
end

Dir[File.join(cwd,'dotfiles','.[a-z]*')].each do |file|
  install_to_home(file)
end

Dir[File.join(cwd,'bin','*')].each do |file|
  install_to_home(file,'bin')
end

